### ISSUE TITLE
example program crashes

### ISSUE THREAD

**Issue by cornservant** [jamescoleuk/fuzzy_finder#1] opened 2022-08-05 21:18 UTC
Upon entering the sequence "sa" into the prompt the program crashes

Output after entering `s`:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/examples/lotr`
   Frodo Baggins
   Bilbo Baggins
   Sméago
   Smaug
   Shelob
   Sauron
   Saruman
>  Samwise Gamgee

$ s
```

then entering the second letter `a`:
```
$ cargo run --example lotr
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/examples/lotr`



thread 'main' panicked at 'byte index 3 is not a char boundary; it is inside 'é' (bytes 2..4) of `Sméagol`', library/core/src/str/mod.rs:127:5
   Shelob                                                                                                                                     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
   Saruman                                   ⏎
```

System info:

```
rustc 1.62.1 (e092d0b6b 2022-07-16)
Linux esprimop510 5.15.57-2-MANJARO #1 SMP PREEMPT Mon Jul 25 01:32:51 UTC 2022 x86_64 GNU/Linux
```

**Comment by jamescoleuk** [comment] 2022-08-05 21:22
Thanks for reporting that. I think I'm doing something funny around the accented character 'é', in 'Sméagol'. I'll fix it.

**Comment by jamescoleuk** [comment] 2022-08-13 14:10
Just pushed a fix (50f5d3f2acba05e4563e5d903966d4220bbd0705). I got to learn about the [challenges of codepoint slicing](https://stackoverflow.com/questions/51982999/slice-a-string-containing-unicode-chars)! Good times. 

If you're on MacOS you can test that it handles chars greater than one byte (say é) by `option+e` followed by `e`. You could in this way find 'Sméagol'.

**Comment by cornservant** [comment] 2022-08-15 00:28
Brilliant!
Here's another challenge for you: If you enter "smagol" and hit return the program does as expected:
![image](https://user-images.githubusercontent.com/3222/184560538-a3335528-3139-4988-b070-dd511ec512a9.png)

However if you enter "smagole" and delete the last letter "e" before hitting return ... we get this crash:
![image](https://user-images.githubusercontent.com/3222/184560600-5e06eac9-84d9-4bf4-815b-ac8f41bdd70c.png)

```
   Sméagol
$ smagolthread 'main' panicked at 'index out of bounds: the len is 8 but the index is 8', /home/long/programming/fuzzy_finder/src/list.rs:89:10
                                        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
              ⏎
```

Now that's puzzling!

**Comment by jamescoleuk** [comment] 2022-08-16 10:24
Thank you! You're my number one. I shall fix the heck out of this.

**Comment by jamescoleuk** [comment] 2022-09-16 06:42
@exit91: @BeLeap got there before me. Thanks BeLeap!

**Comment by cornservant** [comment] 2022-09-16 15:29
Still crashes when selecting the top-most entry, entering let's say "Aragorn" and pressing enter.

https://asciinema.org/a/rCiTGn2JfoYnDXYMlO8DfR2li

**Comment by jamescoleuk** [comment] 2023-01-11 16:52
OK so I know you opened this a long time ago but I had a trying autumn. I've fixed a related issue and I think it might have fixed this one. At least I can't reproduce what you describe when selecting the top entry (the asciinema vid has been archived). Would you please give it a go with lk v0.3.3? Many thanks.

**Comment by cornservant** [comment] 2023-01-11 20:09
Hi James, hope you're doing ok now.
Also I didn't know the asciinema recordings get binned after 7 days, so sorry about that.

Here are the steps to reproduce (on commit 6fe67368be0dc4b1033fe6847c71933d9d62553d)

1. Select top-most entry with arrow-up key ("Watcher in the Water")
```
>  Watcher in the Water
   Ungoliant
   Túrin Turambar
   Tuor and Idril
   Treebeard
   Tom Bombadil
   Thorin Oakenshield
   Thranduil
$ 
```

2. Enter the search term "Aragorn"
```








$ Aragorn
```

4. Press the return key

```



$ Aragornthread 'main' panicked at 'index out of bounds: the len is 8 but the index is 8', /home/long/programming/fuzzy_finder_original/src/list.rs:87:10
                                               note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
                  ⏎   
```

Hope this helps.

**Comment by jamescoleuk** [comment] 2023-01-12 15:32
That was super helpful, thank you. I've fixed it. 

The view wasn't properly resetting when the number of matches went from dozens to 'Aragorn'. Now if the user types anything or deletes anything the selection resets to the bottom. 

It's published in a new version, and incorporated into [lk](https://github.com/jamescoleuk/lk) too.

Thanks again.

**Closed as completed by jamescoleuk** 2023-01-12 15:32 UTC
